// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.user_id", "fef5e7f6-87a1-4867-bc2c-c02426973d89");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1580872319);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1580872559);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1580872439);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1580872289);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 77);
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories.rec.impressions", "{\"53156\":1580872298676,\"53164\":1580872298676,\"53171\":1580872298676}");
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories.spoc.impressions", "{\"2345\":[1580872298707]}");
user_pref("browser.newtabpage.activity-stream.impressionId", "{0807a0cc-0ddb-4874-81e4-e9ee8587be34}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1580803200);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1580872333244");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1580874150244");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1580872304517");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1580875904517");
user_pref("browser.search.region", "US");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1580872297");
user_pref("browser.slowStartup.averageTime", 4593);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20190215001400");
user_pref("browser.startup.homepage_override.mstone", "65.0.1");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 2);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1580872298739");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "65.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "0df889a77d25439b97e38a6831f4d00c");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 28);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "65.0.1");
user_pref("extensions.lastPlatformVersion", "65.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"dcee7e41-0e40-49c5-8af5-87b49a90fd3d\",\"screenshots@mozilla.org\":\"9fe2c138-e098-4470-b018-8276c9e482a3\",\"webcompat-reporter@mozilla.org\":\"b4f65c5f-eee1-4c6e-a49e-e5a31810773c\",\"webcompat@mozilla.org\":\"a020385a-5684-4000-b181-9acdf7bdec05\"}");
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1580872423);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20190215001400");
user_pref("media.gmp-manager.lastCheck", 1580872421);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "14bb54ca-04db-46c8-9167-3fdaa29b0a5e");
user_pref("security.sandbox.plugin.tempDirSuffix", "6c703a1c-4304-4c4e-b172-b95c375dedbf");
user_pref("services.blocklist.addons.checked", 1580843625);
user_pref("services.blocklist.gfx.checked", 1580843625);
user_pref("services.blocklist.onecrl.checked", 1580843625);
user_pref("services.blocklist.pinning.checked", 1580843625);
user_pref("services.blocklist.plugins.checked", 1580843625);
user_pref("services.settings.clock_skew_seconds", 28799);
user_pref("services.settings.last_etag", "\"1580831371709\"");
user_pref("services.settings.last_update_seconds", 1580843625);
user_pref("services.settings.main.language-dictionaries.last_check", 1580843625);
user_pref("services.settings.main.sites-classification.last_check", 1580843625);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1580872287);
user_pref("toolkit.telemetry.cachedClientID", "dc84cd3c-cedb-44b0-92bd-ac5766abe401");
user_pref("toolkit.telemetry.previousBuildID", "20190215001400");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
